-- AlterTable
ALTER TABLE "Statistic" ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Travel" ALTER COLUMN "startDateTime" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "endDateTime" SET DATA TYPE TIMESTAMPTZ;
